I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1666, in script
    show mila normal at ceneter
  File "game/script.rpy", line 1666, in <module>
    show mila normal at ceneter
NameError: name 'ceneter' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1666, in script
    show mila normal at ceneter
  File "/usr/share/renpy/renpy/ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/usr/share/renpy/renpy/ast.py", line 1387, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/usr/share/renpy/renpy/ast.py", line 1387, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/usr/share/renpy/renpy/python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/usr/share/renpy/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1666, in <module>
    show mila normal at ceneter
NameError: name 'ceneter' is not defined

Linux-6.5.13-7-MANJARO-x86_64-with-glibc2.38 x86_64
Ren'Py 8.2.0.0+unofficial
Останній відпочинок 0.1
Sat Jan 27 21:47:43 2024
